---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: {{ .Values.app.container.port }}
    targetPort: {{ .Values.app.container.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicedb.name }}
  namespace: default
spec:
  type: {{ .Values.servicedb.type }}
  externalName: {{ .Values.servicedb.dns }}
  ports:
    - port: {{ .Values.servicedb.port }}