apiVersion: v1
kind: Service
metadata:
  name: network-connection
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    bb: web
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
spec:
  type: {{ .Values.service.type2 }}
  externalName: {{ .Values.service.externalName }}
  ports:
    - port: {{ .Values.service.port2 }}