apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: flask-container
        image: 537646401150.dkr.ecr.eu-west-1.amazonaws.com/flask_repo:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
        volumeMounts:
        - name: myconfigmap
          mountPath: "/app/my.conf"
          readOnly: true
      volumes:
      - name: myconfigmap 
        configMap:
          name: create-conf  

---
apiVersion: v1
kind: Service
metadata:
  name: network-connection
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
spec:
  type: ExternalName
  externalName: ec2-34-254-171-223.eu-west-1.compute.amazonaws.com
  ports:
    - port: 3306
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 5000}]'
spec:
  ingressClassName: alb 
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: network-connection
              port:
                number: 5000
